language: julia
julia:
    - 1.0
    - 1
    - nightly
notifications:
    email: false

after_success:
  - julia -e 'import Pkg; Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("LsqFit")); include(joinpath("docs", "make.jl"))'
